apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-app
  namespace: bms
  labels:
    app: bms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
      - name: bms-ctr
        image: neeraj2806/bms:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000  # Replace with the port your app runs on
--- 

apiVersion: v1
kind: Service
metadata:
  name: bms-service
  namespace: bms
  labels:
    app: bms
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000  # Replace with the port your app runs on
  selector:
    app: bms
